services:
  search-api:
    build:
      context: SearchEngine
      dockerfile: SeachEngineAPI/Dockerfile
    ports:
      - "5001:8080"
    volumes:
      - ./Data:/data  # Mount your local Data folder into container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  load-balancer:
    build:
      context: SearchEngine
      dockerfile: LoadBalancerAPI/Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build:
      context: "C:/Users/brolo/Desktop/it-arkitektur/Semester-6/Arkitektur-principper/SearchEngineV2/SearchEngineV2Font/my-search-engine-app"
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=development
