apiVersion: v1
kind: PersistentVolume
metadata:
  name: indexer-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/seData/medium
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: indexer-pvc
  namespace: searchengine
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
