apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadbalancer
  namespace: searchengine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loadbalancer
  template:
    metadata:
      labels:
        app: loadbalancer
    spec:
      containers:
        - name: loadbalancer
          image: broloes2/search-loadbalancer:latest
          ports:
            - containerPort: 8080