apiVersion: v2
name: searchengine
version: 0.1.0

dependencies:
  - name: searchengine-mongo
    version: 0.1.0
    repository: file://charts/searchengine-mongo
  - name: searchengine-postgres
    version: 0.1.0
    repository: file://charts/searchengine-postgres
  - name: termnet-api
    version: 0.1.0
    repository: file://charts/termnetapi
  - name: search-coordinator
    version: 0.1.0
    repository: file://charts/coordinator
  - name: indexer
    version: 0.1.0
    repository: file://charts/indexer
  - name: redis
    version: 17.3.15
    repository: https://charts.bitnami.com/bitnami
  - name: postgresql
    version: 12.10.1
    repository: https://charts.bitnami.com/bitnami
  - name: mongodb
    version: 16.5.11
    repository: https://charts.bitnami.com/bitnami
    dependencies:
  - name: loki-stack
    version: 2.9.10   
    repository: https://grafana.github.io/helm-charts
  - name: frontend
    version: 0.1.0
    repository: file://charts/frontend
