global:
  scrape_interval: 15s  # How frequently to scrape targets
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'search-api'
    static_configs:
      - targets: ['search-api:8082']

  - job_name: 'load-balancer'
    static_configs:
      - targets: ['load-balancer:8080']

  - job_name: 'termnet'
    static_configs:
      - targets: ['termnet:8083']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
